server:
  port: 8989
  servlet:
     path: / # 访问根路径，默认"/"
  tomcat:
#    uri-encoding: UTF-8 # URI编码，默认"ISO-8859-1"
    max-threads: 300
    max-connections: 200
    accept-count: 100
    basedir: ./work
    accesslog:
      enabled: true

# spring相关设置
spring:
    application:
        name: boot-system
        version: 1.0.0
    profiles:
        active: dev
    aop:
        proxy-target-class: true
    jackson:
        # 序列化日期时以timestamps输出(例如true=1413800730456, false=2014-10-20T10:26:06.604+0000)
        serialization.write_dates_as_timestamps: true
        # 使用自定义 date-format 需禁用 write_dates_as_timestamps 才会生效
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        serialization.fail_on_empty_beans: false
#    messages:
#        #设置国际化配置文件存放在classpath:/i18n目录下
#        basename: i18n/messages
#        #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
#        cache-duration:
#          seconds: 3600
    mvc:
        favicon:
            enabled: false
#        throw-exception-if-no-constant-found: true
#    resources:
#        add-mappings: true
#     spring启动banner设置
    banner:
        charset: UTF-8
        location: classpath:config/banner.txt
    servlet:
        multipart:
          enabled: true
          file-size-threshold: 0 # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则在内存中。默认值为0
          location:
          max-file-size: 100MB # 文件的最大大小
          max-request-size: 1024MB # 单次最大请求大小
    freemarker:
        checkTemplateLocation: false
    datasource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        hikari:
            # 定义获取连接的超时时间。最小250ms,默认30s
            connectionTimeout: 10000
            # 定义连接空闲时间。最小10s,默认10m
            idleTimeout: 50000
            # 定义最小的空闲连接数。推荐不设置。或与最大连接数一致；保持固定的连接数目
            minimumIdle: 10
            # 定义最大的连接数。默认10
            maximumPoolSize: 20
            # 定义连接的最大生命周期。推荐设置该属性。最小30s，默认30m
            # spring.datasource.hikari.maxLifeTime=600000
            # 从连接池获取到连接后，进行检查的查询语句。推荐设置该属性。默认值为none
            connectionTestQuery: select 1
            connection-init-sql: SET NAMES utf8mb4
#        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#        driver-class-name: com.mysql.jdbc.Driver
#        username: root
#        password: 123456

## shiro权限相关设置
#shiro:
#  enabled: true
#  loginUrl: /api/user/login
#  retryCountLimit: 5 #密码错误重试次数
#  web:
#      enabled: true
#  annotations:
#      enabled: false
#      # 设置为false，不使用shiro annotations，如果启用shiro注解，会默认创建DefaultAdvisorAutoProxyCreator，此处会与spring不兼容导致二次代理，在使用shiro注解时controller会失效
logging:
  config: classpath:config/log4j2.xml

# mybatis相关设置
mybatis:
  config-location: classpath:config/mybatis-config.xml
#  mapperLocations: classpath:mappers/*.xml




