spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456


file:
#    file: E:/work/file/
    file: D:/work/file/
#    file: /Users/apple/Desktop/3/img/
    url: http://localhost:8989/
